name: Simple Workflow

on:
  # Déclencheur programmé toutes les heures
  #   - cron: '0 * * * *'

  workflow_dispatch:

jobs:
  main_job:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code source
        run: echo "Récupération du code source"

      - name: Vérification terminée
        run: echo "Vérification terminée"
